/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ParkLAB;







public class exit extends javax.swing.JFrame {

   

    
    public exit() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton btnback = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        Etime = new javax.swing.JTextField();
        Pnumber = new javax.swing.JTextField();
        javax.swing.JButton btnExit = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        Vtype = new javax.swing.JTextField();
        exitTime = new javax.swing.JTextField();
        javax.swing.JButton btnClear = new javax.swing.JButton();
        exitDate = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        Edate = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtexit = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Plate Number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Vehicle Type:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Entry Time:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        Etime.setBackground(java.awt.SystemColor.control);
        getContentPane().add(Etime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, 30));

        Pnumber.setBackground(java.awt.SystemColor.control);
        getContentPane().add(Pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, 30));

        btnExit.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 90, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("Exit Time:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        Vtype.setBackground(java.awt.SystemColor.control);
        getContentPane().add(Vtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 160, 30));

        exitTime.setBackground(java.awt.SystemColor.control);
        getContentPane().add(exitTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 160, 30));

        btnClear.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 90, 30));

        exitDate.setBackground(java.awt.SystemColor.control);
        getContentPane().add(exitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 160, 30));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Exit Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        Edate.setBackground(java.awt.SystemColor.control);
        getContentPane().add(Edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 160, 30));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Entry Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        txtexit.setColumns(20);
        txtexit.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtexit.setRows(5);
        jScrollPane1.setViewportView(txtexit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 140, 410, 380));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Checkout.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
         Home Home = new Home();
        Home.setVisible(true);
        Home.pack();
        Home.setLocationRelativeTo(null);
        this.dispose();      
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
          
       
                
        
        
               txtexit.append("\t\tCheck Out: Exit For Parking!!\n\n" +
                       "Plate Number: \t\t" + Pnumber.getText() + "\n\n" +
                               "Vehicle Type: \t\t" + Vtype.getText() + "\n\n" +
                                       "Entry Time: \t\t\t" + Etime.getText() + "\n\n" +
                                               "Exit Time: \t\t\t" + exitTime.getText() + "\n\n" +
                                                       "Entry Date: \t\t\t" + Edate.getText() + "\n\n" +
                                                               "Exit Date: \t\t\t" + exitDate.getText() + "\n\n" +
                                                                       "===============================================" + "\n\n" +
                                                                       "\t\tThank You For Parking!!" + "\n\n" +
                                                                       "\tYou may now go to counter for payment!!");
        
        
        
        
        
        Pnumber.setText("");
        Vtype.setText("");
        Etime.setText("");
        exitTime.setText("");
        Edate.setText("");
        exitDate.setText("");
    }//GEN-LAST:event_btnExitActionPerformed

 
  
       
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Pnumber.setText("");
            Vtype.setText("");
            Etime.setText("");
              exitTime.setText("");
            Edate.setText("");
              exitDate.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Edate;
    private javax.swing.JTextField Etime;
    private javax.swing.JTextField Pnumber;
    private javax.swing.JTextField Vtype;
    private javax.swing.JTextField exitDate;
    private javax.swing.JTextField exitTime;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtexit;
    // End of variables declaration//GEN-END:variables
}
